/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import Clases.consultas;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class RecuperarForm extends javax.swing.JFrame {

    /**
     * Creates new form RecuperarForm
     */
    public RecuperarForm() {
        initComponents();
        //Centrar el formulario
        // Establecer el título de la ventana
        this.setTitle("Recursos Humanos - Recuperar Contraseña");
        
        //Centrar el formulario
        this.setLocationRelativeTo(this);
        
        // Cargar el logo como icono de la ventana desde los recursos del proyecto
        ImageIcon logo = new ImageIcon(getClass().getResource("/imagenes/icono.png"));
        this.setIconImage(logo.getImage());
        
        jTextUser2.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                // Convertir el carácter a minúscula si es una letra mayúscula
                if (Character.isUpperCase(c)) {
                    e.setKeyChar(Character.toLowerCase(c));
                }
                // Verificar si el carácter ingresado es una letra sin acento
                if (!Character.isLetter(c) || !isLatinLetter(c)) {
                    e.consume(); // Si no es válido, lo eliminamos
                }
                
                // Verificar el tamaño máximo de caracteres
                if (jTextUser2.getText().length() >= 10) {
                    e.consume(); // Si el tamaño es mayor o igual a 10, no permitir más caracteres
                }
            }

            private boolean isLatinLetter(char c) {
                // Comprobar si el carácter es una letra del alfabeto latino básico sin acentos
                return (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z');
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextUser2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextRecordar = new javax.swing.JTextField();
        jbtnvolver2 = new javax.swing.JButton();
        jbtnrecuperar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(jLabel1.getFont().deriveFont((float)24));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recuperar Contraseña");

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/userLabel.png"))); // NOI18N
        jLabel3.setText("Usuario:");

        jTextUser2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jTextUser2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextUser2.setName("jTextUsuario"); // NOI18N
        jTextUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUser2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/key.png"))); // NOI18N
        jLabel4.setText("Mostrar Clave:");

        jTextRecordar.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jTextRecordar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextRecordar.setName("jTextUsuario"); // NOI18N
        jTextRecordar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRecordarActionPerformed(evt);
            }
        });

        jbtnvolver2.setBackground(new java.awt.Color(204, 255, 255));
        jbtnvolver2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jbtnvolver2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/previous.png"))); // NOI18N
        jbtnvolver2.setText("Volver");
        jbtnvolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnvolver2ActionPerformed(evt);
            }
        });

        jbtnrecuperar.setBackground(new java.awt.Color(204, 255, 255));
        jbtnrecuperar.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jbtnrecuperar.setText("Recuperar");
        jbtnrecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnrecuperarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jTextUser2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextRecordar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jbtnvolver2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jbtnrecuperar)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextUser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextRecordar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnvolver2)
                    .addComponent(jbtnrecuperar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUser2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUser2ActionPerformed

    private void jTextRecordarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRecordarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRecordarActionPerformed

    private void jbtnvolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnvolver2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        LoginForm f2=new LoginForm();
        f2.setVisible(true); 
    }//GEN-LAST:event_jbtnvolver2ActionPerformed

    private void jbtnrecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnrecuperarActionPerformed
        consultas con = new consultas();
    String usuario = jTextUser2.getText(); // Obtener el usuario del campo de texto
    String contraseña = con.obtenerContraseñaPorUsuario(usuario); // Obtener la contraseña
    
    // Verificar si se encontró la contraseña
    if (contraseña != null) {
        jTextRecordar.setText(contraseña); // Mostrar la contraseña en el campo jTextRecordar
    } else {
        jTextRecordar.setText(""); // Limpiar el campo si no se encontró el usuario
         // Mostrar mensaje de error
    }

    }//GEN-LAST:event_jbtnrecuperarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextRecordar;
    private javax.swing.JTextField jTextUser2;
    private javax.swing.JButton jbtnrecuperar;
    private javax.swing.JButton jbtnvolver2;
    // End of variables declaration//GEN-END:variables
}
