/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import Clases.consultas;
import javax.swing.JOptionPane;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
/**
 *
 * @author angel
 */
public class registroForm extends javax.swing.JFrame {

    /**
     * Creates new form registroForm
     */
    public registroForm() {
        initComponents();
        // Establecer el título de la ventana
        this.setTitle("Recursos Humanos - Registro");
        
        //Centrar el formulario
        this.setLocationRelativeTo(this);
        
        // Cargar el logo como icono de la ventana desde los recursos del proyecto
        ImageIcon logo = new ImageIcon(getClass().getResource("/imagenes/icono.png"));
        this.setIconImage(logo.getImage());
        
     // Configurar KeyListener para el campo de texto jTextNuevo
        jTextNuevo.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                // Convertir el carácter a minúscula si es una letra mayúscula
                if (Character.isUpperCase(c)) {
                    e.setKeyChar(Character.toLowerCase(c));
                }
                // Verificar si el carácter ingresado es una letra sin acento
                if (!Character.isLetter(c) || !isLatinLetter(c)) {
                    e.consume(); // Si no es válido, lo eliminamos
                
                }
                // Verificar el tamaño máximo de caracteres
                if (jTextNuevo.getText().length() >= 10) {
                    e.consume(); // Si el tamaño es mayor o igual a 10, no permitir más caracteres
                }
            }

            private boolean isLatinLetter(char c) {
                // Comprobar si el carácter es una letra del alfabeto latino básico sin acentos
                return (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z');
            }
        });
        jTextClave.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                // Verificar el tamaño máximo de caracteres
                if (jTextClave.getText().length() >= 10) {
                    e.consume(); // Si el tamaño es mayor o igual a 10, no permitir más caracteres
                }
            }
        });
        jTextPass2.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                // Verificar el tamaño máximo de caracteres
                if (jTextPass2.getText().length() >= 10) {
                    e.consume(); // Si el tamaño es mayor o igual a 10, no permitir más caracteres
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextNuevo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextClave = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jTextPass2 = new javax.swing.JPasswordField();
        jbtnvolver = new javax.swing.JButton();
        jbtnregistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(jLabel1.getFont().deriveFont((float)24));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrate");

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario:");

        jTextNuevo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jTextNuevo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextNuevo.setName("jTextUsuario"); // NOI18N
        jTextNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNuevoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Clave:");

        jTextClave.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jTextClave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextClave.setName("jTextPass"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirmar:");

        jTextPass2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jTextPass2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextPass2.setName("jTextPass"); // NOI18N

        jbtnvolver.setBackground(new java.awt.Color(204, 255, 255));
        jbtnvolver.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jbtnvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/previous.png"))); // NOI18N
        jbtnvolver.setText("Volver");
        jbtnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnvolverActionPerformed(evt);
            }
        });

        jbtnregistrar.setBackground(new java.awt.Color(204, 255, 255));
        jbtnregistrar.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jbtnregistrar.setText("Registrarse");
        jbtnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnregistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNuevo)
                            .addComponent(jTextClave)
                            .addComponent(jTextPass2))
                        .addGap(74, 74, 74))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnvolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(jbtnregistrar)
                        .addGap(65, 65, 65))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnvolver)
                    .addComponent(jbtnregistrar))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNuevoActionPerformed
        // TODO add your handling code here:
        // Agregar un KeyListener para validar el texto ingresado
    }//GEN-LAST:event_jTextNuevoActionPerformed

    private void jbtnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnvolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        LoginForm f2=new LoginForm();
        f2.setVisible(true);
    }//GEN-LAST:event_jbtnvolverActionPerformed

    private void jbtnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnregistrarActionPerformed
        // Obtener el texto de los campos
    String user = jTextNuevo.getText();
    String clave = new String(jTextClave.getPassword());
    String pass = new String(jTextPass2.getPassword());
    
    // Verificar que todos los campos estén llenos
    if (user.isEmpty() || clave.isEmpty() || pass.isEmpty()) {
        // Mostrar mensaje de advertencia si algún campo está vacío
        JOptionPane.showMessageDialog(null, "Todos los campos deben llenarse");
        return; // Salir del método sin realizar el registro
    }
    
    // Verificar si el usuario ya existe
    consultas con = new consultas();
    if (con.usuarioExiste(user)) {
        // Mostrar mensaje si el usuario ya está registrado
        JOptionPane.showMessageDialog(null, "Este usuario ya existe. \nSelecciona un nuevo usuario.");
        return; // Salir del método sin realizar el registro
        // Limpiar los campos después del registro
    }
    
    // Comparar las contraseñas
    if (clave.equals(pass)) {
        // Llamar al método para guardar el usuario en la base de datos
        con.guardarUsuario(user, clave);
        
        // Limpiar los campos después del registro
        jTextNuevo.setText("");
        jTextClave.setText("");
        jTextPass2.setText("");
        
        JOptionPane.showMessageDialog(null, "Registro exitoso");
    } else {
        // Mensaje de error si las contraseñas no coinciden
        JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
    }
    }//GEN-LAST:event_jbtnregistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registroForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jTextClave;
    private javax.swing.JTextField jTextNuevo;
    private javax.swing.JPasswordField jTextPass2;
    private javax.swing.JButton jbtnregistrar;
    private javax.swing.JButton jbtnvolver;
    // End of variables declaration//GEN-END:variables

    
}
